Barrberrr/Controllers/EmailSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Barrberrr.Models;
using System.Net;
using System.Net.Mail;


namespace Barrberrr.Controllers
{
    public class EmailSetupController : Controller
    {
        // GET: EmailSetup
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Barrberrr.Models.Gmail model)
        {
            MailMessage mm = new MailMessage("phucnguyenthanhhong@gmail.com", model.Email);
            mm.Subject = model.Phone;
            mm.Body = model.Message;
            mm.IsBodyHtml = false;

            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.EnableSsl = true;

            NetworkCredential nc = new NetworkCredential("phucnguyenthanhhong@gmail.com", "pxbirdisnumber1");
            smtp.UseDefaultCredentials = true;
            smtp.Credentials = nc;
            smtp.Send(mm);
            ViewBag.Message = "Mail Has Been Sent Successfully";
            return View();
        }
        // GET: /EmailSetup/Complete
        public ActionResult Complete()
        {
            return View();
        }
    }
}

Barrberrr/Controllers/HomeController.cs
using Barrberrr.EntityContext;
using Barrberrr.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Barrberrr.Controllers
{
    public class HomeController : Controller
    {
        HairStoreEntities storeDB = new HairStoreEntities();
        //
        // GET: /Home/
        public ActionResult Index()
        {
            // Get most popular albums
            var products = GetTopSellingAlbums(5);
            return View(products);
        }
        public List<Product> GetTopSellingAlbums(int count)
        {
            // Group the order details by album and return
            // the albums with the highest count
            return storeDB.Products
                .OrderByDescending(a => a.OrderDetails.Count())
                .Take(count)
                .ToList();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult Service()
        {
            return View();
        }
    }
}

Barrberrr/Views/Home/Contact.cshtml
@model Barrberrr.Models.Gmail
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Hair Salon a Beauty and spa Category Flat Bootstrap Responsive Website Template | Contact :: w3layouts</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Hair Salon Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/zoomslider.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/style.css" />
    <link href="~/Content/css/font-awesome.css" rel="stylesheet">
    <script type="text/javascript" src="~/Content/js/modernizr-2.6.2.min.js"></script>
    <!--/web-fonts-->
    <link href="//fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
    <!--//web-fonts-->
</head>
<body>
    <!--/main-header-->
    <!--/banner-section-->
    <!--/banner-section-->
    <div id="demo-1" class="banner-inner">
        <!--/header-w3l-->     
            <div class="contact-top-agileits two">
                <div class="col-md-4 contact-grid ">
                    <div class="contact-grid1 agileits-w3layouts">
                        <div class="con-w3l-info">
                            <h4>Address </h4>
                            <p>141 Điện Biên Phủ <span>Hồ Chí Minh City.</span></p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="col-md-4 contact-grid">
                    <div class="contact-grid2 w3">
                        <div class="con-w3l-info">
                            <h4>Call Us</h4>
                            <p>+1234 567 890</p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="col-md-4 contact-grid">
                    <div class="contact-grid3 w3l">
                        <div class="con-w3l-info">
                            <h4>Email</h4>
                            <p><a href="mailto:info@example.com">info@example.com</a>

                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>

            </div>
            <!--//header-w3l-->

        </div>
   
    <!--//banner-section-->
    <!--//main-header-->
    <!-- breadcrumb -->
    <div class="w3_breadcrumb">
        <div class="breadcrumb-inner">
            <ul>
                <li><a href="index.html">Home</a> <i>//</i></li>

                <li>Contact</li>
            </ul>
        </div>
    </div>
    <!-- //breadcrumb -->
    <!--/content-inner-section-->
   
    <div class="w3_content_agilleinfo_inner">
        @using (Html.BeginForm("Index", "EmailSetup", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="container">
                <div class="title-agileits">
                    <h2 class="w3l-agile">Contact Us</h2>
                </div>
                <div class="w3_mail_grids">
                    <form action="#" method="post">
                        <div class="col-md-6 w3_agile_mail_grid">
                            <table>
                                <tr>
                                    <td>
                                        @*<input type="text" placeholder="Your Name" required="">*@
                                        Your Name:
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.Name)
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @*<input type="email" placeholder="Your Email" required="">*@
                                        Email:
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.Email)
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @*<input type="text" placeholder="Your Phone Number" required="">*@
                                        Phone:
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.Phone)
                                    </td>
                                </tr>
                            </table>

                        </div>
                        <div class="col-md-6 w3_agile_mail_grid">
                            <table>
                                <tr>
                                    <td>
                                        @*<textarea name="Message" placeholder="Your Message" required=""></textarea>*@
                                        Message:
                                    </td>
                                    <td>@Html.TextAreaFor(model => model.Message,new { rows="2",cols="55"})</td>
                                </tr>
                                <tr>
                                    <td><input type="submit" value="Submit"/></td>
                                </tr>
                            </table>   
                            
                        </div>         
                        <span style="color:green">@ViewBag.Message</span>
                        <div class="clearfix"> </div>
                    </form>
                </div>
            </div>

        }
        <div class=" map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.1829177609347!2d106.70118731474427!3d10.797298261760671!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528b0af6c8691%3A0x764e0f592a64d478!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBLaW5oIHThur8gVMOgaSBjaMOtbmggVFAuSENN!5e0!3m2!1svi!2s!4v1618499078712!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
    </div>
    <!--//content-inner-section-->

    <a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
    <script type="text/javascript" src="~/Content/js/jquery-2.1.4.min.js"></script>
    <!-- Dropdown-Menu-JavaScript -->
    <script>$(document).ready(function(){
					$(".dropdown").hover(
						function() {
							$('.dropdown-menu', this).stop( true, true ).slideDown("fast");
							$(this).toggleClass('open');
						},
						function() {
							$('.dropdown-menu', this).stop( true, true ).slideUp("fast");
							$(this).toggleClass('open');
						}
					);
				});</script>
    <!-- //Dropdown-Menu-JavaScript -->
    <!-- pop-up-box -->
    <script src="~/Content/js/main.js"></script>
    <!-- pop-up-box -->
    <script src="~/Content/js/lightbox-plus-jquery.min.js"></script>
    <!--//pop-up-box -->
    <!--/script-->
    <script type="text/javascript" src="~/Content/js/move-top.js"></script>
    <script type="text/javascript" src="~/Content/js/easing.js"></script>
    <script type="text/javascript">jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});</script>
    <script type="text/javascript">$(document).ready(function() {
							/*
							var defaults = {
					  			containerID: 'toTop', // fading element id
								containerHoverID: 'toTopHover', // fading element hover id
								scrollSpeed: 1200,
								easingType: 'linear'
					 		};
							*/

							$().UItoTop({ easingType: 'easeOutQuart' });

						});</script>
    <!--end-smooth-scrolling-->
    <!--js for bootstrap working-->
    <script src="~/Content/js/bootstrap.js"></script>
    <!-- //for bootstrap working -->
</body>
</html>