Barrberrr/Controllers/StoreManagerController.cs
using Barrberrr.EntityContext;
using Barrberrr.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Barrberrr.Controllers
{

    [Authorize(Roles = "Admin")]
    public class StoreManagerController : Controller
    {
        private HairStoreEntities db = new HairStoreEntities();

        // GET: /StoreManager/
        public ActionResult Index(string searchString)
        {
            var products = db.Products.Include(a => a.Brand).Include(a => a.Genre);
           
            //var st = from m in db.Products
            //         select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                 products = products.Where(s => s.Title.Contains(searchString));
            }
            return View(products.ToList());
        }

        // GET: /StoreManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: /StoreManager/Create
        public ActionResult Create()
        {
            
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name");
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,GenreId,BrandId,Title,Price,ProductArtUrl")] Product product)
        {
            
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", product.BrandId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", product.GenreId);
            return View(product);
        }

        // GET: /StoreManager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", product.BrandId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", product.GenreId);
            return View(product);
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,GenreId,BrandId,Title,Price,ProductArtUrl")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Added;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", product.BrandId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", product.GenreId);
            return View(product);
        }

        // GET: /StoreManager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {               
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /StoreManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();          
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Barrberrr/Views/StoreManager/Create.cshtml
@model Barrberrr.Models.Product
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/View.cshtml";}
<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, "GenreId", new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownList("GenreId", String.Empty)              
                @Html.ValidationMessageFor(model => model.GenreId)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "BrandId", new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownList("BrandId", String.Empty)
                @Html.ValidationMessageFor(model => model.ProductId)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductArtUrl, new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.ProductArtUrl)
                @Html.ValidationMessageFor(model => model.ProductArtUrl)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Barrberrr/Views/StoreManager/Delete.cshtml
@model Barrberrr.Models.Product
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/View.cshtml";}
<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Brand.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductArtUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductArtUrl)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Barrberrr/Views/StoreManager/Details.cshtml
@model Barrberrr.Models.Product
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/View.cshtml";}
<h2>Details</h2>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Brand.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductArtUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductArtUrl)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Barrberrr/Views/StoreManager/Edit.cshtml
@model Barrberrr.Models.Product
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/View.cshtml";
}
<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ProductId)
        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, "GenreId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreId", String.Empty)
                @Html.ValidationMessageFor(model => model.GenreId)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BrandId, "BrandId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrandId", String.Empty)
                @Html.ValidationMessageFor(model => model.BrandId)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductArtUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductArtUrl)
                @Html.ValidationMessageFor(model => model.ProductArtUrl)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Barrberrr/Views/StoreManager/Index.cshtml
@model IEnumerable<Barrberrr.Models.Product>
@helper Truncate(string input, int length)
{
    if (input.Length <= length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text>...</text>
    }
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/View.cshtml";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
    @using (Html.BeginForm("Index", "StoreManager", FormMethod.Get))
    {
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

    </p>
    <table class="table">
        <tr>
            <th>
                Brand
            </th>
            <th>
                Genre
            </th>
            <th>
                Title
            </th>
            <th>
                Price
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Truncate(item.Brand.Name, 25)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre.Name)
                </td>
                <td>
                    @Truncate(item.Title, 25)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ProductId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ProductId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ProductId })
                </td>
            </tr>
        }
    </table>